import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import Clock from "@/components/Clock";
import Footer from "@/components/Footer";
import BirthdayList from "@/components/BirthdayList";

export default function Home({ birthdays }) {
  return (
    <>
      <Head>
        <title>It is your birthday</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="App">
        <Clock birthdays={birthdays} />
        <Footer />
        <BirthdayList list={birthdays} />
        <Link href="/admin" className="userLink">
          <Image width={30} height={30} src="/user-icon.svg" alt="user icon" />
        </Link>
      </div>
    </>
  );
}

export async function getStaticProps() {
  const url =
    process.env.NODE_ENV === "development"
      ? "http://localhost:3000"
      : "https://itisyourbirthday.vercel.app";

  let res = await fetch(url + "/api/getBirthdays")
    .then((res) => res.json())
    .then((data) => {
      return data;
    });

  let birthdays = await res;

  return {
    props: { birthdays },
  };
}
