import { useState } from "react";

import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import styles from "@/styles/Register.module.css";

function Register() {
  const [userCreated, setUserCreated] = useState({
    name: "placeholder",
    isCreated: false,
  });
  const [emailExists, setEmailExists] = useState(false);
  const [userInfo, setUserInfo] = useState({
    email: "",
    password: "",
    name: "",
  });

  const handleSubmit = async (e) => {
    e.preventDefault();
    let userInput = {
      ...userInfo,
    };

    // Make call to backend to create user
    const res = await fetch("/api/user/create", {
      method: "POST",
      body: JSON.stringify(userInput),
      headers: {
        "Content-Type": "application/json",
      },
    });

    if (res.ok) {
      const data = await res.json();
      setUserCreated({ name: data.user.name, isCreated: true });
    } else if (res.status == 409) {
      setEmailExists(true);
    } else {
      console.log("something wrong");
    }
  };
  return (
    <>
      <Head>
        <title>It is your birthday</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="App">
        <div className={styles.login}>
          <h1>Make a new account.</h1>

          <form className={styles.form} onSubmit={handleSubmit}>
            <input
              type="text"
              name="name"
              id="name"
              placeholder="Enter your name . . ."
              value={userInfo.name}
              onChange={({ target }) =>
                setUserInfo({ ...userInfo, name: target.value })
              }
            />
            <input
              type="email"
              name="email"
              id="email"
              placeholder="Enter your email . . ."
              value={userInfo.email}
              onChange={({ target }) =>
                setUserInfo({ ...userInfo, email: target.value })
              }
            />
            <input
              type="password"
              name="password"
              id="password"
              placeholder="Enter your password . . ."
              value={userInfo.password}
              min={6}
              onChange={({ target }) =>
                setUserInfo({ ...userInfo, password: target.value })
              }
            />
            <input type="submit" value="Login" />
          </form>

          {userCreated.isCreated && (
            <div className={styles.success}>
              Hello {userCreated?.name}! You have successfully registered. You
              can log in <Link href="/">here</Link>
            </div>
          )}
          {emailExists && (
            <div className={styles.fail}>
              Email already exists. Try another one.
            </div>
          )}
          <div className={styles.register}>
            Already have an account?
            <Link href="/">Sign in here</Link>
          </div>
        </div>
      </div>
      <Link href="/" className="userLink">
        <Image
          width={30}
          height={30}
          src="/arrow-left-solid.svg"
          alt="user icon"
        />
      </Link>
    </>
  );
}

export default Register;
